# Generated by Django 5.0.4 on 2024-04-24 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provinsi', models.CharField(max_length=250)),
                ('kabupaten', models.CharField(max_length=250)),
                ('jenis_kelamin', models.IntegerField()),
                ('usia', models.IntegerField()),
                ('agama', models.CharField(max_length=100)),
                ('menikah', models.IntegerField()),
                ('pendidikan', models.IntegerField()),
                ('pekerjaan', models.IntegerField()),
                ('kub', models.FloatField()),
                ('toleransi', models.FloatField()),
                ('kesetaraan', models.FloatField()),
                ('kerjasama', models.FloatField()),
                ('tahun', models.IntegerField()),
            ],
        ),
    ]
