# Generated by Django 5.0.4 on 2024-05-23 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_province_cluster'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cluster',
            new_name='ClusterModel',
        ),
    ]
