# Generated by Django 5.0.4 on 2024-05-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_cluster_clustermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='province',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
