# Generated by Django 5.0.4 on 2024-06-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_province_latitude_province_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='province',
            name='longitude',
        ),
        migrations.AddField(
            model_name='clustermodel',
            name='kerjasama',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='clustermodel',
            name='kesetaraan',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='clustermodel',
            name='toleransi',
            field=models.FloatField(null=True),
        ),
    ]
